# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: required
# dist: xenial

services:
  - docker

language: minimal
cache: packages

before_install:
  - docker --version
  # - docker pull fbachl/inlabru:latest
  - docker run --name my_ubuntu -v /$(pwd):/home/work -it -d fbachl/inlabru:latest /bin/bash
  - docker ps
  - docker container ls --all
  - docker exec -it my_ubuntu ls -al /home
  - docker exec -it my_ubuntu ls -al /home/work
  #- docker exec -it my_ubuntu "echo $PATH"
  #- docker exec -it my_ubuntu "echo $PKG_CONFIG_PATH"
  #- sudo apt-get -y install pkg-config # Not sure this is in the image
  #- sudo apt-get -y install libgit2-dev libcurl4-openssl-dev libssl-dev # for git2r (devtools requirement)
  
install:
  # - docker exec -it my_ubuntu R -e "install.packages('devtools')"
  # - docker exec -it my_ubuntu R -e "devtools::install_deps(pkg='/home/work',dep = T)"
  # - docker exec -it my_ubuntu /bin/bash sudo R -e "install.packages('sp', 'ggplot2')"
  # 'testthat, ggmap, rgl, sphereplot, raster, dplyr, maptools, mgcv, shiny, spatstat, spatstat.data, RColorBrewer, graphics, knitr, rmarkdown)"
  - docker exec -it my_ubuntu R -e ".libPaths()"
  - docker exec -it my_ubuntu R -e "getwd()"
script:
  - docker exec -it my_ubuntu R CMD build /home/work/
  - docker exec -it my_ubuntu ls -al /
  - docker exec -it my_ubuntu R CMD check /home/work