# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: required
# dist: xenial

services:
  - docker

language: r
cache: packages

before_install:
  - docker --version
  # - docker pull fbachl/inlabru:latest
  - docker run -v /$(pwd):/home/work -it -d fbachl/inlabru /bin/bash
  # - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  # - sudo apt-get --yes --force-yes update -qq
  # - sudo apt-get install libgdal-dev libgeos-dev libproj-dev
  #  libudunits2-dev libv8-dev libprotobuf-dev protobuf-compiler libjq-dev

install:
  - docker exec -it fbachl/inlabru R -e 'devtools::install_deps(dep = T)'

script:
  - docker exec -it fbachl/inlabru R CMD build /home/work/
  - docker exec -it fbachl/inlabru R CMD check /home/work/*tar.gz