# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

group: travis_latest
language: R
dist: xenial
sudo: false
cache: packages

r:
# - oldrel
 - release
# - devel

addons:
  apt:
    packages:
      - libgeos-dev
      - libproj-dev
      - libgdal-dev

install:
  - R -e 'install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)'

# r_build_args: --resave-data

r_check_args: --as-cran --run-donttest --timings

# r_check_args: --as-cran --timings
