# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: required

services:
  - docker
dist: xenial
language: r
cache: packages

before_install:
#  - "docker pull ubuntu:16.04"
#  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
#  - sudo apt-get --yes --force-yes update -qq
#  - sudo apt-get install libgdal-dev libgeos-dev libproj-dev libudunits2-dev libv8-dev libprotobuf-dev protobuf-compiler libjq-dev
  - docker pull r-base
  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"
r_packages:
  - sp
  - rgdal
  - rgeos



# r_build_args: --resave-data

r_check_args: --as-cran --run-donttest --timings

# r_check_args: --as-cran --timings
