# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: required
# dist: xenial

services:
  - docker

language: minimal
cache: packages

before_install:
  - docker --version
  - docker run --name my_ubuntu -v /$(pwd):/home/work -it -d fbachl/inlabru:latest /bin/bash
  - docker ps
  - docker container ls --all

install:
  - docker exec -it my_ubuntu ls -al /home
  - docker exec -it my_ubuntu ls -al /home/work
  - docker exec -it my_ubuntu whoami
  - docker exec -it my_ubuntu R -e ".libPaths()"
  - docker exec -it my_ubuntu R -e "getwd()"
  - docker exec -it my_ubuntu R -e "devtools::session_info()"
  - docker exec -it my_ubuntu ls /usr/local/lib/R/site-library
  - docker exec -it my_ubuntu ls /usr/lib/R/site-library
  - docker exec -it my_ubuntu ls /usr/lib/R/library
  # - docker exec -it my_ubuntu R -e "devtools::install_deps(pkg='/home/work',dep = TRUE)"

script:
  # We need to be in a tmp directory because travis_wait generates a file that R CHECK will complain about.
  - mkdir tmp
  - cd tmp
  - travis_wait 60 sleep infinity & docker exec -it my_ubuntu R -e "quit('no',status=length(do.call(c, as.list(devtools::check('/home/work', run_dont_test=TRUE)))))"
  

  #- docker exec -it my_ubuntu R CMD build /home/work/
  #- docker exec -it my_ubuntu ls -al /
  #- docker exec -it my_ubuntu R CMD check /home/work